package tests.contacts;// Generated by Selenium IDE


import model.ContactDate;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;
import tests.TestBase;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

public class CreateContactTests extends TestBase {

    @Test
    public void createContact() {
        app.contacts().createContact(new ContactDate().withFirstName("Ivan").withPhoto("src/test/resources/images/avatar.png"));
    }

    @Test
    public void createContacts() {
        app.contacts().createContact(new ContactDate("","idea1", "idea2", "idea3", ""));
    }

    public static List<ContactDate> contactProvider() {
        var result = new ArrayList<ContactDate>();
        for (var name : List.of("", "first_name")) {
            for (var header : List.of("", "middle_name")) {
                for (var footer : List.of("", "last_name")) {
                    for (var photo : List.of("", "src/test/resources/images/avatar.png")) {
                        result.add(new ContactDate("", name, header, footer, photo));
                    }
                }
            }
        }
        for (int i = 0; i < 6; i++) {
            result.add(new ContactDate("", randomString(i), randomString(i), randomString(i),randomFile("src/test/resources/images")));
        }
        return result;
    }

    @ParameterizedTest
    @MethodSource("contactProvider")
    public void canCreateMultipleContacts(ContactDate contact) {
        int contactCount = app.contacts().getContactCount();

        app.contacts().createContact(contact);

        int newContactCount = app.contacts().getContactCount();
        Assertions.assertEquals(contactCount + 1, newContactCount);
    }

    @ParameterizedTest
    @MethodSource("contactProvider")
    public void canCreateMultipleContact(ContactDate contacts) {
        var oldContacts = app.contacts().getList();
        app.contacts().createContact(contacts);
        var newContacts = app.contacts().getList();
        //Сравниваем два числа, ид групп
        Comparator<ContactDate> compareById = (o1, o2) -> {
            return Integer.compare(Integer.parseInt(o1.id()), Integer.parseInt(o2.id()));
        };
        newContacts.sort(compareById);

        var expectedList = new ArrayList<>(oldContacts);
        var contactWithId = contacts.withId(newContacts.get(newContacts.size() - 1).id())
                .withMiddleName("")
                .withPhoto("");

        expectedList.add(contactWithId);
        expectedList.sort(compareById);
        Assertions.assertEquals(newContacts, expectedList);
    }
}