package tests.contacts;// Generated by Selenium IDE


import model.ContactDate;
import org.junit.jupiter.api.Test;
import tests.TestBase;

public class CreateContactTests extends TestBase {

    @Test
    public void createContact() {
        app.contacts().createContact(new ContactDate());
    }

    @Test
    public void createGroup() {
        app.contacts().createContact(new ContactDate("idea1", "idea2", "idea3"));
    }
}