package tests.contacts;// Generated by Selenium IDE


import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import model.ContactDate;
import model.GroupDate;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;
import tests.TestBase;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

public class CreateContactTests extends TestBase {

    @Test
    public void createContact() {
        app.contacts().createContact(new ContactDate()
                .withFirstName("Ivan")
                .withPhoto("src/test/resources/images/avatar.png"));
    }

    @Test
    public void createContactInGroup() {
        if (app.hmb().getGroupCount() == 0) {
            app.hmb().createGroup(new GroupDate("", "ff", "ff", "ff"));
        }
        var group = app.hmb().getGroupList().get(0);

        var oldRelated = app.hmb().getContactsInGroup(group);
        app.contacts().createContactInGroup(new ContactDate()
                .withFirstName("Ivan")
                .withPhoto("src/test/resources/images/avatar.png"), group);
        var newRelated = app.hmb().getContactsInGroup(group);
        Assertions.assertEquals(oldRelated.size()+1, newRelated.size());
    }

    @Test
    public void createContacts() {
        app.contacts().createContact(new ContactDate("","idea1", "idea2", "idea3", ""));
    }

    public static List<ContactDate> contactProvider() throws IOException {
        var result = new ArrayList<ContactDate>();
        for (var name : List.of("", "first_name")) {
            for (var header : List.of("", "middle_name")) {
                for (var footer : List.of("", "last_name")) {
                    for (var photo : List.of("", "src/test/resources/images/avatar.png")) {
                        result.add(new ContactDate("", name, header, footer, photo));
                    }
                }
            }
        }
//        for (int i = 0; i < 6; i++) {
//            result.add(new ContactDate("", CommonFunctions.randomString(i), CommonFunctions.randomString(i), CommonFunctions.randomString(i),randomFile("src/test/resources/images")));
//        }
//        return result;

        var json = Files.readString(Paths.get("contacts.json"));

        ObjectMapper mapper = new ObjectMapper();
        var value = mapper.readValue(json, new TypeReference<List<ContactDate>>(){});
        result.addAll(value);
        return result;
    }

    @ParameterizedTest
    @MethodSource("contactProvider")
    public void canCreateMultipleContacts(ContactDate contact) {
        long  contactCount = app.hmb().getContactCount();

        app.contacts().createContact(contact);

        long  newContactCount = app.hmb().getContactCount();
        Assertions.assertEquals(contactCount + 1, newContactCount);
    }

    @ParameterizedTest
    @MethodSource("contactProvider")
    public void canCreateMultipleContact(ContactDate contacts) {
        var oldContacts = app.hmb().getContactList();
        app.contacts().createContact(contacts);
        var newContacts = app.hmb().getContactList();
        //Сравниваем два числа, ид групп
        Comparator<ContactDate> compareById = (o1, o2) -> {
            return Integer.compare(Integer.parseInt(o1.id()), Integer.parseInt(o2.id()));
        };
        newContacts.sort(compareById);

        var maxId = newContacts.get(newContacts.size() - 1).id();

        var expectedList = new ArrayList<>(oldContacts);
        var contactWithId = contacts.withId(newContacts.get(newContacts.size() - 1).id())
                .withPhoto("");

        expectedList.add(contactWithId);
        expectedList.sort(compareById);
        Assertions.assertEquals(newContacts, expectedList);
    }
}